import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Calendar, Download, AlertCircle } from 'lucide-react';
import { EnergyReading } from '@/types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface ExportPDFModalProps {
    isOpen: boolean;
    onClose: () => void;
    history: EnergyReading[];
    userName: string;
}

export function ExportPDFModal({ isOpen, onClose, history, userName }: ExportPDFModalProps) {
    const [dateRange, setDateRange] = useState<'today' | 'week' | 'month' | 'all'>('all');
    const [isExporting, setIsExporting] = useState(false);

    if (!isOpen) return null;

    const generatePDF = () => {
        setIsExporting(true);

        setTimeout(() => {
            try {
                const now = Date.now();
                let filteredData = history;

                // Filter by selected range
                if (dateRange === 'today') {
                    const startOfDay = new Date().setHours(0, 0, 0, 0);
                    filteredData = history.filter(r => r.timestamp >= startOfDay);
                } else if (dateRange === 'week') {
                    const sevenDaysAgo = now - (7 * 24 * 60 * 60 * 1000);
                    filteredData = history.filter(r => r.timestamp >= sevenDaysAgo);
                } else if (dateRange === 'month') {
                    const thirtyDaysAgo = now - (30 * 24 * 60 * 60 * 1000);
                    filteredData = history.filter(r => r.timestamp >= thirtyDaysAgo);
                }

                if (filteredData.length === 0) {
                    alert("No data available for the selected time period.");
                    setIsExporting(false);
                    return;
                }

                const doc = new jsPDF({ orientation: 'landscape', format: 'a4' });

                // --- Branding & Header ---
                doc.setFillColor(15, 23, 42); // slate 900
                doc.rect(0, 0, 297, 40, 'F');

                doc.setTextColor(255, 255, 255);
                doc.setFontSize(24);
                doc.setFont("helvetica", "bold");
                doc.text("ONXY EDGE", 14, 20);

                doc.setFontSize(12);
                doc.setFont("helvetica", "normal");
                doc.setTextColor(148, 163, 184); // slate 400
                doc.text("Energy Consumption & Telemetry Report", 14, 28);

                // Report Meta
                doc.setFontSize(10);
                doc.setTextColor(255, 255, 255);
                const reportDate = new Date().toLocaleDateString('en-GB') + ' ' + new Date().toLocaleTimeString('en-US');
                doc.text(`Generated: ${reportDate}`, 200, 20);
                doc.text(`Generated by: ${userName}`, 200, 26);
                const rangeText = dateRange === 'all' ? 'All Time' : dateRange === 'today' ? 'Today' : dateRange === 'week' ? 'Last 7 Days' : 'Last 30 Days';
                doc.text(`Time Period: ${rangeText}`, 200, 32);

                // --- Summary Stats ---
                const totalEnergy = filteredData[filteredData.length - 1].energy - filteredData[0].energy;
                const totalCost = totalEnergy > 0 ? totalEnergy * 7.50 : 0;
                const avgVoltage = filteredData.reduce((acc, curr) => acc + curr.voltage, 0) / filteredData.length;

                doc.setTextColor(15, 23, 42);
                doc.setFontSize(14);
                doc.setFont("helvetica", "bold");
                doc.text("Summary Statistics", 14, 55);

                doc.setFontSize(11);
                doc.setFont("helvetica", "normal");
                doc.text(`Total Energy Consumed: ${totalEnergy > 0 ? totalEnergy.toFixed(3) : 0} kWh`, 14, 65);
                doc.text(`Estimated Cost: ₹${totalCost.toFixed(2)}`, 14, 72);
                doc.text(`Average Voltage: ${avgVoltage.toFixed(1)} V`, 14, 79);
                doc.text(`Total Data Points: ${filteredData.length}`, 14, 86);

                // --- Table Data ---
                const ELECTRICITY_RATE = 7.50; // ₹ per kWh
                const tableData = filteredData.map(r => {
                    const date = new Date(r.timestamp);
                    const cost = r.energy * ELECTRICITY_RATE;
                    return [
                        date.toLocaleDateString() + ' ' + date.toLocaleTimeString(),
                        r.voltage.toFixed(2),
                        r.current.toFixed(3),
                        r.power.toFixed(2),
                        r.energy.toFixed(4),
                        (r.carbonFootprint || 0).toFixed(4),
                        `₹${cost.toFixed(2)}`
                    ];
                });

                autoTable(doc, {
                    startY: 100,
                    head: [['Timestamp', 'Voltage (V)', 'Current (A)', 'Power (W)', 'Energy (kWh)', 'Carbon (kg)', 'Cost']],
                    body: tableData,
                    theme: 'striped',
                    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: 'bold' },
                    alternateRowStyles: { fillColor: [248, 250, 252] },
                    styles: { fontSize: 9, cellPadding: 4, halign: 'center' },
                    columnStyles: { 0: { halign: 'left' } },
                    margin: { top: 100 }
                });

                // --- Footer ---
                const pageCount = (doc as any).internal.getNumberOfPages();
                for (let i = 1; i <= pageCount; i++) {
                    doc.setPage(i);
                    doc.setFontSize(8);
                    doc.setTextColor(148, 163, 184); // slate 400
                    doc.text(`Page border: ONXY EDGE Confidential - Page ${i} of ${pageCount}`, 14, 200);
                }

                doc.save(`onxy_edge_${dateRange}_report.pdf`);
                onClose();
            } catch (error) {
                console.error('Error generating PDF', error);
                alert('Failed to generate PDF. Make sure you have adequate data.');
            } finally {
                setIsExporting(false);
            }
        }, 100);
    };

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-50 flex items-center justify-center px-4 sm:px-0 bg-slate-900/40 dark:bg-slate-900/60 backdrop-blur-sm">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95, y: 10 }}
                    animate={{ opacity: 1, scale: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95, y: 10 }}
                    transition={{ type: "spring", duration: 0.4 }}
                    className="bg-white dark:bg-slate-900 w-full max-w-md rounded-3xl shadow-2xl overflow-hidden border border-slate-200/50 dark:border-slate-800"
                >
                    {/* Header */}
                    <div className="bg-slate-50 dark:bg-slate-800/50 px-6 py-5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            <div className="w-10 h-10 rounded-2xl bg-blue-500/10 text-blue-600 flex items-center justify-center">
                                <Download size={20} />
                            </div>
                            <div>
                                <h3 className="text-lg font-bold text-slate-900 dark:text-white leading-tight">Export PDF Report</h3>
                                <p className="text-sm text-slate-500 dark:text-slate-400">Select time period for actual telemetry.</p>
                            </div>
                        </div>
                        <button
                            onClick={onClose}
                            className="p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl transition-colors"
                        >
                            <X size={20} />
                        </button>
                    </div>

                    {/* Body */}
                    <div className="p-6 space-y-6">
                        <div className="space-y-3">
                            <label className="text-sm font-semibold text-slate-700 dark:text-slate-300">Time Period</label>
                            <div className="grid grid-cols-2 gap-3">
                                {[
                                    { id: 'today', label: 'Today', sub: 'Since 12:00 AM' },
                                    { id: 'week', label: 'Last 7 Days', sub: 'Past week' },
                                    { id: 'month', label: 'Last 30 Days', sub: 'Past month' },
                                    { id: 'all', label: 'All Time', sub: 'Current session' }
                                ].map((opt) => (
                                    <button
                                        key={opt.id}
                                        onClick={() => setDateRange(opt.id as any)}
                                        className={`flex flex-col items-start p-4 rounded-2xl border-2 transition-all duration-200 ${dateRange === opt.id
                                                ? 'border-blue-500 bg-blue-50 dark:bg-blue-500/10'
                                                : 'border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 hover:border-blue-200 dark:hover:border-blue-800'
                                            }`}
                                    >
                                        <span className={`font-semibold ${dateRange === opt.id ? 'text-blue-700 dark:text-blue-400' : 'text-slate-700 dark:text-slate-300'}`}>
                                            {opt.label}
                                        </span>
                                        <span className={`text-[11px] ${dateRange === opt.id ? 'text-blue-500 dark:text-blue-500/80' : 'text-slate-500'}`}>
                                            {opt.sub}
                                        </span>
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-4 border-t border-slate-100 dark:border-slate-800">
                            <div className="flex items-center gap-2 text-[11px] text-amber-600 dark:text-amber-500 bg-amber-50 dark:bg-amber-500/10 px-3 py-1.5 rounded-lg w-full sm:w-auto">
                                <AlertCircle size={14} className="shrink-0" />
                                <p>Exports Real Firebase Data Only.</p>
                            </div>
                            <button
                                onClick={generatePDF}
                                disabled={isExporting}
                                className="w-full sm:w-auto px-6 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-semibold transition-all active:scale-95 disabled:opacity-50 disabled:scale-100 flex items-center justify-center gap-2"
                            >
                                {isExporting ? (
                                    <>
                                        <div className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin" />
                                        Generating...
                                    </>
                                ) : (
                                    <>
                                        <Download size={18} />
                                        Download PDF
                                    </>
                                )}
                            </button>
                        </div>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
}
